"use strict";
var ENVIRONMENT;
(function (ENVIRONMENT) {
    ENVIRONMENT[ENVIRONMENT["LOCAL"] = 0] = "LOCAL";
    ENVIRONMENT[ENVIRONMENT["DEVELOPMENT"] = 1] = "DEVELOPMENT";
    ENVIRONMENT[ENVIRONMENT["STAGING"] = 2] = "STAGING";
    ENVIRONMENT[ENVIRONMENT["PRODUCTION"] = 3] = "PRODUCTION";
})(ENVIRONMENT || (ENVIRONMENT = {}));
function runTests(envTesting) {
    console.log(`Test results are ${envTesting}`);
}
runTests(ENVIRONMENT.LOCAL);
runTests(ENVIRONMENT.DEVELOPMENT);
runTests(ENVIRONMENT.STAGING);
runTests(ENVIRONMENT.PRODUCTION);
